### ISSUE TITLE
Can you do it for Q&A too?

### ISSUE THREAD

**Issue by fedekrum** [olegkoval/magento-contacts_form_captcha#2]
This feature will be great to have on the Q&A. I get bots posting spam on them.
Thanks

**Comment by olegkoval** [comment]
Hello. Could you, please, decipher the abbreviation "Q&A". Because looks like this is not a "Quality assurance". It's a "Questions & Answers" page (or something like this)?

**Comment by fedekrum** [comment]
haa...sorry. You are right. It is not on magentos default. is a 3rd party extension.
For this http://www.pandawebstudio.com/projects/free-magento-product-qa-extension

**Comment by olegkoval** [comment]
Easier to modify a "Product QA" extension instead of creating additional extension for extension.
