### ISSUE TITLE
Does is support to reCaptcha v2?

### ISSUE THREAD

**Issue by kjenagan** [olegkoval/magento-contacts_form_captcha#5]
Hi, Thank you for this awesome extension. Wonder is this extension will continue support once the google reCAPTCHA stop support for V1 from March 2018? will there be any code alternation? Thank you.

**Comment by olegkoval** [comment]
Hello Jenagan.

Thank you for your question.
The latest version of this extension (v1.4.0) use a newest version of reCaptcha - V2. So, you just need to update extension to v1.4.0.

Best regards,
Oleg Koval
